### ISSUE TITLE
Handler: StructuredDiskBatchHandler -> Source Schema Validation, Disk Storage

### ISSUE THREAD

**Issue by turbolytics** [turbolytics/sql-flow#94]
This handler will allow for inserting source data into a table of a known structure. It is related to #93. 

The purpose of this task is to allow the end user to define the SQL associated with the source messages. Each source message will be insert against this schema, verifying the schema early in the message pipeline.

This will also relate to #41.

The way I imagine this is:

- User configures their pipeline with the `handlers.StructuredDiskBatchHandler`

https://github.com/turbolytics/sql-flow/blob/main/dev/config/examples/attach-geoip.yml#L25-L27
```
 handler:
    type: 'handlers.StructuredDiskBatch'
    sql: |
        The PipelineSQL
    structured_disk_batch:
       database: path/to/the/duckdb/database.db
       table: the_table_to_use
```

Unlike the `SturcturedMemBatchHandler` in #93, this handler will require defining the table schema and database outside of SQLFlow. SQLFlow will use an already created table that lives on disk to buffer the pipeline batch. This allows users to manage the table and database file however they want.
